#!/usr/bin/env bash
# Install a HAProxy service and configure 2 machines

# update and upgrade packages system
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y haproxy

# Configure HAProxy init script
echo "ENABLED=1" >> /etc/default/haproxy

# Create Backup of haproxy.cfg and haproxy file
sudo cp /etc/default/haproxy /etc/default/haproxy.bak
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.bak

# configure Round Robin for webservers
echo "
# LOAD BALANCED POOL
frontend front
        bind *:80
	    default_backend web-back
backend web-back
        balance roundrobin
        server 300-web-01 35.237.197.183:80 check
        server 300-web-02 35.237.134.117:80 check" >> /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy reload
sudo service haproxy restart
