#!/usr/bin/env bash
#print Holberton School 10 times using for loop
i=1
while [  $i -lt 11 ]
 do 
 if [ $i == 4 ]
	then 
	echo "bad luck"
 elif [ $i == 8 ]
	then 
	echo "good luck"
else
  	echo "Holberton School"
	  fi
	i=$(( i+1 ))
done
