#!/usr/bin/env bash
#verify if a file exist and print message
NFILE=holbertonschool
if [ -e "$NFILE" ]
	then 
	echo "$NFILE file exists"
		if [ -s "$NFILE" ]
			then
			echo "$NFILE file is not empty"
		else
			echo "$NFILE file is empty"
		fi
		if [ -f "$NFILE" ]
			then
			echo "$NFILE is a regular file"
		fi
else
	echo "$NFILE file does not exists"
fi
