#!/usr/bin/env bash
#verify if a file exist and print message
file="holbertonschool"
if [ -e "$file" ]
	then 
	echo "holbertonschool file exists"
		if [ ! -s "$file" ]
		then
		echo "$file file is empty"
		else
		echo "$file file is not empty"
		fi
		if [ -f "$file" ]
		then
		echo "$file is a regular file"
		fi
else
	echo "$file file does not exists"
fi
