#!/usr/bin/env bash
#verify if a file exist and print message

NFILE=holbertonschool
if [ -e "$NFILE" ]
then 
echo "holbertonschool file exists"
if [ -s "$NFILE" ]
then
echo "holbertonschool file is not empty"
else
echo "holbertonschool file is empty"
fi
if [ -f "$NFILE" ]
then
echo "holbertonschool is a regular file"
fi
else
echo "holbertonschool file does not exists"
fi
